# This workflow will do a clean installation of ubuntu, build the source code and run tests/linting on the code to make sure that it's compliant.

name: Markdown Lint CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: markdownlint-cli2-action
      uses: DavidAnson/markdownlint-cli2-action@v19.1.0
      with:
        config: .markdownlint-cli2.yaml
